version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: blog01-db
    environment:
      POSTGRES_DB: blog01
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - blog01_data:/var/lib/postgresql/data
    networks:
      - blog_network

  backend:
    build: ./demo
    container_name: blog-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blog01
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: "true"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - blog_network

  frontend:
    build: ./zero1blog-frontend
    container_name: blog-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - blog_network

volumes:
  blog01_data:

networks:
  blog_network:
    driver: bridge
